### ISSUE TITLE
Visual artifacts in Chrome

### ISSUE THREAD

**Issue by gciruelos** [susam/mathb#11]
[This is actually a bug from MathJax](https://github.com/mathjax/MathJax/issues/1300), and it has been fixed in newer vesions, so simply updating the version that mathb.in uses should solve the bug.

**Comment by relrod** [comment]
+1 can this please be done/deployed?

**Comment by susam** [comment]
Thanks for bumping up this issue. The latest version of MathJax has been deployed now. This issue should be resolved now.
