### ISSUE TITLE
Problems rendering side-by-side underbrace

### ISSUE THREAD

**Issue by Evidlo** [susam/mathb#14]
The input `$\underbrace{123}_{123}\underbrace{123}_{123}$` doesn't render correctly on mathb.in as shown [here](http://mathb.in/20975).

However, on another MathJax rendering site, [it works fine](https://arachnoid.com/latex/?equ=%24%5Cunderbrace%7B123%7D_%7B123%7D%5Cunderbrace%7B123%7D_%7B123%7D%24)

**Comment by susam** [comment]
This is no longer an issue in the current version of MathB. Please see issue #8 for resolution notes.
