### ISSUE TITLE
I can't find the license

### ISSUE THREAD

**Issue by Akuli** [susam/mathb#15]
The end of the README says that there's a LICENSE.md somewhere, but I can't find one from the repo. The README also says "please visit \<a link\> to obtain a copy of the license", but the link brings me to a mathb.in page saying "This post does not exist."

**Comment by susam** [comment]
Thank you for reporting this. The broken link has been fixed: http://mathb.in/5

I will put the LICENSE.md file later.

**Comment by susam** [comment]
The broken link has been removed. The license is available here: https://github.com/susam/mathb/blob/main/LICENSE.md
