### ISSUE TITLE
Doesn't understand bcancel. 

### ISSUE THREAD

**Issue by stevem995** [susam/mathb#19]
![Mathb-paste-bcancel-issue](https://user-images.githubusercontent.com/7109207/86020215-a1267680-b9f5-11ea-99eb-130c11a87e80.PNG)

**Comment by susam** [comment]
Thank you for creating this issue and providing an example input that reproduces the issue. This has now been fixed in commit b3599c9b981f8b9f30dfbd4afe3f1c7f6656ad53. See https://mathb.in/72999 for a demo of the fix.
