### ISSUE TITLE
In the tutorial, the text column shows doubled backslashes where only one should be.

### ISSUE THREAD

**Issue by bbeeton15** [susam/mathb#20]
The first paragraph of the tutorial explains how to input inline math.  The input window shows the correct code but in the "text" output, backslashes are doubled.  The problem persists throughout.

I've encountered this problem elsewhere, and it's lethal when trying to explain (La)TeX conventions.  Unfortunately, I have no idea how to fix the problem, but unless it *is* fixed, someone trying to learn from this is likely to become confused unnecessarily.

**Comment by susam** [comment]
Resolved as part of #8. Please see https://mathb.in/1 for the updated tutorial which does not use double-blackslashes anymore. Please see #8 for resolution notes.
