### ISSUE TITLE
Needs MathJax 2, not the 3 that it grabs from the git clone

### ISSUE THREAD

**Issue by AzzieDev** [susam/mathb#21]
As soon as I cloned the current version of MathJax 2.7.9 which was released on August 25th, 2020, everything worked properly.

https://github.com/mathjax/MathJax/releases/tag/2.7.9

Download, extract to the "thirdparty" directory, rename the directory you extracted to just "MathJax" and not with the version number.

**Comment by susam** [comment]
MathB is now written in Common Lisp and it now uses MathJax v3.2. The project at https://github.com/susam/mathb/blob/main/README.md now has a step that tells the reader to run `make setup`. This command sets up MathJax v3.2 automatically and other dependencies, so that MathB can run successfully.
