### ISSUE TITLE
Need to download "pagedown" manually

### ISSUE THREAD

**Issue by AzzieDev** [susam/mathb#22]
Since it's hosted on Google Code, which is now in a frozen archived state, download it from there and extract to "thirdparty" directory, and make sure the directory you just extracted is named "pagedown".

https://code.google.com/archive/p/pagedown/source/default/source

There may be newer forks or releases of pagedown that are maintained, but I don't know which would be supported.

**Comment by susam** [comment]
MathB now uses https://github.com/markedjs/marked (a JavaScript library that supports GitHub Flavoured Markdown, a strict superset of the CommonMark specification). The documentation at https://github.com/susam/mathb/blob/main/README.md has been updated with steps to install `marked` and other dependencies to set up an environment where MathB can run successfully.
