### ISSUE TITLE
Problem rendering part of demo page

### ISSUE THREAD

**Issue by AzzieDev** [susam/mathb#23]
http://mathb.in/1

At the bottom, for 

`When this is combined with \eqref{summation} we obtain \eqref{theorem}.`

it returns

` When this is combined with (???) we obtain (???).`

My suspicion is something changed with MathJax and it was updated on the main site, but this line was overlooked or forgotten about or was like that, to begin with.

**Comment by susam** [comment]
This was fixed in a recent rewrite of MathB. As a result, this is no longer an issue. See https://mathb.in/1 for a demo of the `\eqref` working successfully.
