### ISSUE TITLE
Behave nicely when printing the page and provide a print preview

### ISSUE THREAD

**Issue by kieranclancy** [susam/mathb#3]
Currently when printing the page, you get all the MathB.in header/footer as well as two columns, one with code and one with the math content.

I think it would be nice if only the math content were printed. In other words, if you could get something similar to what you would get if you ran LaTeX over the document and printed the result.

**Comment by susam** [comment]
This has been resolved in commit fcf3e96. To see an example of the print preview, go to https://mathb.in/1 and select File > Print from the web browser menu. The print preview should not display header, footer, and the form elements anymore. Instead, it should display only the rendered content now.
