### ISSUE TITLE
Code textarea should be larger and move when scrolling

### ISSUE THREAD

**Issue by kieranclancy** [susam/mathb#5]
When writing a long document, such as http://mathb.in/1, you can no longer see the bottom of the content as you write, because the textarea sits at the top of the page while the new content is previewed below the visible window area.

It would be much better if:
1) The code textarea expanded to fill as much space as possible inside the window.
2) The code form including the textarea moved with the window

That way, as you scrolled down a long page, the textarea would move with it and always be as large as possible (until reaching the top or bottom where it would need to be a bit shorter).

**Comment by susam** [comment]
The textarea is resizable in most modern browsers. Please resize the textarea to suit your needs as the length of the rendered content becomes too long.
