### ISSUE TITLE
Integral symbol is rendered incorrectly in Firefox

### ISSUE THREAD

**Issue by Venemo** [susam/mathb#6]
Hi,

It seems to me that integral signs are rendered to small in Firefox. For example, this snippet: http://mathb.in/17534 results in the following:
http://venemo.net/owncloud/public.php?service=files&t=4019eefbc365c09d459f31919b154973

I'm not sure if this is an issue with mathb or mathjax, but thought it's worth reporting.

**Comment by susam** [comment]
MathB.in now uses MathJax 3.2.2. The integral sign appears to be of the correct size with this version of MathJax.
